apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-ns
roleRef:
  kind: ClusterRole
  name: unprivileged_psp
  apiGroup: rbac.authorization.k8s.io
subjects:
# Authorize all authenticated users in a namespace. (both users and service accounts)
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:authenticated
